version: '3'

services:

    frontend:
        container_name: 'frontend-standalone'
        image: metodosagilesutn2020/frontend
        restart: always
        ports:
            - "30000:80"
        env_file:
            - ./config.env